### ISSUE TITLE
gitbook docker demos fail

### ISSUE THREAD

**Issue by brenzi** [integritee-network/book#33]
gitbook instructions to build teeracle docker demo fail:

https://docs.integritee.network/4-development/4.6-demos/4.6.3-teeracle-demo

```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -f docker-compose.yml -f demo-teeracle.yml build --build-arg WORKER_MODE_ARG=teeracle
```
fails with
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid service name 'integritee-node-${VERSION}' - only [a-zA-Z0-9\._\-] characters are allowed
```
Instructions in the README at https://github.com/integritee-network/worker/blob/fd78d5c4939130f2d08a4947c419ef590f50a63f/docker/README.md

work for the build.

but then, even the instructions in the readme fail:
`docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) up demo-teeracle --exit-code-from demo-teeracle`
yields

```
[+] Running 4/4
 ⠿ Network fd_integritee-test-network          Created                                                                                                0.1s
 ⠿ Container fd-integritee-node--1             Created                                                                                                0.0s
 ⠿ Container fd-integritee-teeracle-worker--1  Created                                                                                                0.0s
 ⠿ Container fd-demo-teeracle-1                Created                                                                                                0.1s
Attaching to fd-demo-teeracle-1
dependency failed to start: container fd-integritee-teeracle-worker--1 is unhealthy

```

please check all instructions in gitbook and adjust accordingly

**Comment by OverOrion** [comment]
Just a brief summary of why the teeracle with DCAP could fail:

- The teeracle needs the `TEERACLE_INTERVAL_SECONDS` environment variable specified.
- The `dcap` feature needs to be passed to the makefile via docker `--build-arg` 
- `LD_LIBRARY_PATH` must **NOT** contain the `urts` library of the `aesmd_service`, it will override the default one, which will result in a weird SGX enclave initialization errors.

I will be addressing the last two issues in a PR, because they will be required soon anyhow.

----

This command should be used for building a teeracle with DCAP:
```
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) build --build-arg WORKER_MODE_ARG=teeracle --build-arg WORKER_FEATURES_ARG=dcap --build-arg SGX_MODE=HW 
```

Running it is a bit more challenging and needs some networking adjustments for the containers to reach the specified PCCS server (if the server is on the host). I believe @mosonyi will be able to help with that part.

**Comment by OverOrion** [comment]
There are still some rough edges, but it works:

```
SGX_PROVISION=/dev/sgx/provision SGX_ENCLAVE=/dev/sgx/enclave AESMD=/var/run/aesmd TEERACLE_INTERVAL_SECONDS=600 docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) up demo-teeracle --exit-code-from demo-teeracle
``` 

And make sure `/etc/sgx_default_qcnl.conf` is in the container as well (or just mount the one from the host):
```diff
git diff ./demo-teeracle.yml
diff --git a/docker/demo-teeracle.yml b/docker/demo-teeracle.yml
index be003c61..d2526fbd 100644
--- a/docker/demo-teeracle.yml
+++ b/docker/demo-teeracle.yml
@@ -15,6 +15,7 @@ services:
       - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
     volumes:
       - "${AESMD:-/dev/null}:/var/run/aesmd"
+      - "/etc/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf"
     build:
       context: ${PWD}/..
       dockerfile: build.Dockerfile

```

**Comment by brenzi** [comment]
reproducing on :node-2.cluster.securitee.tech

```
SGX_PROVISION=/dev/sgx/provision SGX_ENCLAVE=/dev/sgx/enclave AESMD=/var/run/aesmd TEERACLE_INTERVAL_SECONDS=600 docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) up demo-teeracle --exit-code-from demo-teeracle
...
 ✔ Container fd-integritee-node--1             Running                                                                                      0.0s 
 ✔ Container fd-integritee-teeracle-worker--1  Running                                                                                      0.0s 
Attaching to fd-demo-teeracle-1
```

in another terminal
```
docker logs fd-integritee-teeracle-worker--1 -f
```
this seems to work, but logs are misleading: see https://github.com/integritee-network/worker/pull/1311

**Comment by brenzi** [comment]
we can now run it against a rococo node:
```
diff --git a/docker/demo-teeracle.yml b/docker/demo-teeracle.yml
index be003c61..3ed3bfcf 100644
--- a/docker/demo-teeracle.yml
+++ b/docker/demo-teeracle.yml
@@ -15,6 +15,7 @@ services:
       - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
     volumes:
       - "${AESMD:-/dev/null}:/var/run/aesmd"
+      - "/etc/sgx_default_qcnl.conf:/etc/sgx_default_qcnl.conf"
     build:
       context: ${PWD}/..
       dockerfile: build.Dockerfile
@@ -36,8 +37,8 @@ services:
       retries: 25
     entrypoint:
         "/usr/local/bin/integritee-service --clean-reset --ws-external -M integritee-teeracle-worker -T wss://integritee-teeracle-worker
-        -u ws://integritee-node -U ws://integritee-teeracle-worker -P 2011 -w 2101 -p 9912 -h 4645
-        run --dev ${ADDITIONAL_RUNTIME_FLAGS} --teeracle-interval ${TEERACLE_INTERVAL_SECONDS}s"
+        -u wss://rococo.api.integritee.network -p 443 -U ws://integritee-teeracle-worker -P 2011 -w 2101 -h 4645
+        run ${ADDITIONAL_RUNTIME_FLAGS} --teeracle-interval ${TEERACLE_INTERVAL_SECONDS}s"
     restart: always
   demo-teeracle:

```
then run it and check the log for the TEE account. You'll need to fund that account with ~10 TEER on rococo and then restart the containers. you may need to kill the existing ones with
```
docker ps
docker stop fd-integritee-node--1
docker stop fd-integritee-teeracle-worker--1
```
then, it should actually run, but our extrinsic fails:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xa034e39930406f27f96028aa2aa331a51bb317d10203d38021b9e8cd88d0e270

**Comment by brenzi** [comment]
several issues:
* we need to run in production mode to succeed our desired flow. this is not nicely feasible with arguments in the docker build
* this means we need to sign the extrinsic which is nontrivial with the docker setup 
* we need to skip Marblerun stuff explicitly or it will hang there

however, apart from the failutes, it would work like this:
build fresh docker containers
COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) build --build-arg WORKER_MODE_ARG=teeracle --build-arg WORKER_FEATURES_ARG=dcap --build-arg SGX_MODE=HW 
run compose
export TEERACLE_INTERVAL_SECONDS=600
SGX_PROVISION=/dev/sgx/provision SGX_ENCLAVE=/dev/sgx/enclave AESMD=/var/run/aesmd TEERACLE_INTERVAL_SECONDS=600 docker compose -f <(envsubst < docker-compose.yml) -f <(envsubst < demo-teeracle.yml) up demo-teeracle --exit-code-from demo-teeracle

check the log

docker logs fd-integritee-teeracle-worker--1 -f

1. check that the enclave runs in production mode!
2. check enclave account: TEE account: 5CsTJAB9PVw6vyM5kLGzV9VPXWiip8A7LPF9Rnd2PNyNy8Re (this will change with each rebuild of the container, but not with restarting compose)

fund it with 10 TEER!

docker stop fd-integritee-teeracle-worker--1

registerQuotingEnclave succeeds
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x96de4c73a76e2f4b726f33d9e5ff8bb7eb0088716729dc774302b0172022b69a

registerTcbInfo is included but fails. teeracle ignores error:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0xe052ea7fd2169bb9e4617cc1a44bec2a566836efe419075a7e6dd9ea392bab63

registerDcapEnclave is included, but fails. teeracle ignores error:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.integritee.network#/explorer/query/0x1adf675d7f7e5bc15acb72a929379cbf069b99fb20196522ceb93b45d722d448

**Comment by brenzi** [comment]
fixed in docs
