### ISSUE TITLE
rebranding

### ISSUE THREAD

**Issue by brenzi** [integritee-network/book#9]
replace all SubstraTEE by Integritee. Modify  Copyright notice to include both SCS and Integritee AG

like here:https://github.com/integritee-network/pallet-teerex/blob/2b5ab50435b6dadcb033a562977196ccbe72f7ef/src/lib.rs#L2-L14

**Comment by echevrier** [comment]
Update the  `Get the docker image ...  https://hub.docker.com/repository/docker/scssubstratee/substratee_dev ` ? In howto_client_tx.md ?

**Comment by echevrier** [comment]
what sould be CName? www.substratee.com

**Comment by brenzi** [comment]
We'll fix CNAME and docker path separately. leave it for now

**Comment by echevrier** [comment]
Replace substratee-worker, substratee-client and substraTEE-registry throughout the project when [#274](https://github.com/integritee-network/worker/issues/274) and [#348](https://github.com/integritee-network/worker/issues/348) have be done.

**Comment by echevrier** [comment]
Replace www.substratee.com throughout the project whe CName fixed

**Comment by echevrier** [comment]
What about code_documentation : Code Documentation for M4 ?

**Comment by echevrier** [comment]
What about roadmap.md : substraTEE-registry and substraTEE STF ?

**Comment by echevrier** [comment]
What about [https://github.com/integritee-network/substraTEE](https://github.com/integritee-network/substraTEE) ? Ex in interoperability-bridges

**Comment by echevrier** [comment]
I don't find any Copyright notice in the book but :
- Integritee is developed by Supercomputing Systems AG and has been supported by grants from the Web3 Foundation: in introduction.md ?
- In Readme.md: (c) Supercomputing Systems AG, 2020
- In remote attestation: SCS is looking into options how to apply such policy to a decentralized system with Intel.

**Comment by echevrier** [comment]
When to use - ?

- When Integritee node, when integritee-node ? 
- What about integritee-worker, integritee-signer, integritee-bridge.... ? 
- What about substraTEE-signer, substraTEE-stealth-node?

What about following sentences (in howto_stf.md): 

> "The blockchain we'll be using is based on parity's **node-template** with one **integritee-specific** pallet " ? 

> "Integritee encapsulates all the **application-specific** stuff in its..." ?

What about  (in scaling-layers.svg):

> Integritee-based parachain / parathread ?

**Comment by echevrier** [comment]
What about substraTEE-logo-scs.svg ?

**Comment by echevrier** [comment]
Link https://github.com/scs/substraTEE-worker/tree/master/app doesn't work. In substraTEE-worker-overview.svg
What about substraTEE-worker-app?
What about substratee_proxy?

**Comment by echevrier** [comment]
Integritee capitalized or lower case? 
For the now I assume that Integritee is always capitalized, except in integritee-node, integritee-worker, integritee-signer, integritee-enclave, ...

**Comment by echevrier** [comment]
How to fix references to https://github.com/scs/substraTEE ? The link is forwarded to https://github.com/integritee-network/substraTEE , which is archived.
- In interoperability-bridges:
The set of integritee-bridge instances is unpermissioned, so anyone with suitable HW can register as a integritee-bridge along the design of **[substraTEE](https://github.com/integritee-network/substraTEE)**. A threshold signature scheme is applied in order to supply *Redeemability* and *Liveness*.

**Comment by echevrier** [comment]
Rework substraTEE-vision.png? Used in design.md.

**Comment by brenzi** [comment]
The remaining questions are not straightforward. We can discuss them next week. Can you please already open a PR with what you have done?

**Comment by echevrier** [comment]
I'm checking the pictures and I will then make a PR

**Comment by echevrier** [comment]
Still unclear:
- Code Documentation for M4 (code_documentation.md)? Nothing done there
- Roadmap? Nothing done there
- Some links:
  1. In attestation_registry_sequence.svg: https://github.com/scs/substraTEE-worker/blob/23e77cab0a0687cda04fd8ef59ba3161e223ce66/worker/src/enclave/api.rs#L319 and https://github.com/scs/substraTEE-node/blob/426be9801e3de1a0a6dc7f6e9db9ee10aa34e5f4/pallets/substratee-registry/host-calls/src/remote_attestation.rs#L180-L199 and ... 
  2. In integritee-worker-overview.svg: https://github.com/scs/substraTEE-worker/tree/master/app
  3. In interoperability.md :  https://github.com/integritee-network/substraTEE
- picture: substraTEE-vision.pngt
- integritee-registry module? Should it not be integritee teerex pallet?
- what about integritee proxy module?
